### ISSUE TITLE
Arch Linux repository `jk-aur`: Key ID discrepancy.

### ISSUE THREAD

**Issue by dreirund** [jstkdng/aur#10]
At https://wiki.archlinux.org/title/Unofficial_user_repositories#jk-aur, the OpenPGP ID `3DEA62513C8035383A245A12E5786B42E8E5D565` is given for the signing key for the repository `jk-aur`.

However, the repository itself reports another key:

```
error: jk-aur: key "4490FF6B512EDCB78A69323F92BA500565FD1CB0" is unknown
```

Is there a corruption, or is the [documentation in the wiki](https://wiki.archlinux.org/title/Unofficial_user_repositories#jk-aur) out of date?

**Comment by jstkdng** [comment]
I have a signing subkey in the repo, that's why they have different key ids

**Comment by dreirund** [comment]
On Tue, 29 Jun 2021 20:01:04 -0700, JustKidding
***@***.***> wrote about "Re: [jstkdng/aur] Arch Linux
repository `jk-aur`: Key ID discrepancy. (#10)":

> I have a signing subkey in the repo, that's why they have different
> key ids

OK, but in order to install a package from the repo I need at first a
valid key for the repo ... (if I do not say pacman to ignore
signatures) ...

How to bootstrap this _properly_?



-- 
Planung ist der Ersatz des Zufalls durch den Irrtum.

**Comment by jstkdng** [comment]
are the instructions in the README.md not working?

**Comment by dreirund** [comment]
On Wed, 30 Jun 2021 08:48:57 -0700, JustKidding
***@***.***> wrote about "Re: [jstkdng/aur] Arch Linux
repository `jk-aur`: Key ID discrepancy. (#10)":

> are the instructions in the README.md not working?

There is mentioned the same key as is mentioned in the [Arch Wiki](https://wiki.archlinux.org/title/Unofficial_user_repositories#jk-aur).

I start over with all keys for ***@***.***` removed from the pacman keyring.

When I do

```
pacman-key -r 3DEA62513C8035383A245A12E5786B42E8E5D565
pacman-key --lsign-key 3DEA62513C8035383A245A12E5786B42E8E5D565
```

and then do a

```
pacman -Syy
```

after adding your repo to the `/etc/pacman.conf`, I get a

```
error: jk-aur: signature from "JustKidding ***@***.***>" is unknown trust
```

`pacman-key --list-keys 3DEA62513C8035383A245A12E5786B42E8E5D565` does print out:

```
pub   rsa4096 2019-08-08 [C]
      3DEA62513C8035383A245A12E5786B42E8E5D565
uid           [  full  ] JustKidding ***@***.***>
uid           [  full  ] [jpeg image of size 5933]
```

and `pacman-key --edit-key 3DEA62513C8035383A245A12E5786B42E8E5D565` is a bit more verbose with

```
pub  rsa4096/E5786B42E8E5D565
     created: 2019-08-08  expires: never       usage: C   
     trust: unknown       validity: full
sub  rsa4096/EF79EFDAFA2323F3
     created: 2019-08-08  expired: 2020-08-07  usage: S   
sub  rsa4096/92BA500565FD1CB0
     created: 2019-08-08  expired: 2020-08-07  usage: S   
sub  rsa4096/ACDE898C8A2D479F
     created: 2019-08-08  expired: 2020-08-07  usage: S   
sub  rsa4096/2F9700B80265A84A
     created: 2019-08-08  expired: 2020-08-07  usage: S   
sub  rsa4096/EF06BB7EBE3CA982
     created: 2019-08-08  expired: 2020-08-07  usage: S   
sub  rsa4096/A85C434A46402E52
     created: 2019-08-08  expired: 2020-08-07  usage: E   
[  full  ] (1). JustKidding ***@***.***>
[  full  ] (2)  [jpeg image of size 5933]
```

It can be seen that trust is full.

`pacman-key --list-keys | less` and searching for ***@***.***` also only gives this one key, so there is no other key with the same user ID `pacman` could errorneosly mean with the "unknown trust"-message.

`pacman-key --list-sigs 3DEA62513C8035383A245A12E5786B42E8E5D565` returns

```
pub   rsa4096 2019-08-08 [C]
      3DEA62513C8035383A245A12E5786B42E8E5D565
uid           [  full  ] JustKidding ***@***.***>
sig 3        E5786B42E8E5D565 2019-08-08  JustKidding ***@***.***>
sig   L      A9F4C5361A124CFA 2021-06-30  Pacman Keyring Master Key ***@***.***>
uid           [  full  ] [jpeg image of size 5933]
sig 3        E5786B42E8E5D565 2019-08-08  JustKidding ***@***.***>
sig   L      A9F4C5361A124CFA 2021-06-30  Pacman Keyring Master Key
***@***.***>
```

Other repositories with signing keys also worked, simply by just doing a `pacman-key --recv-keys <key-ID>` followed by `pacman-key --lsign-key <key-ID>`.

Any idea what could be wrong here?


Btw.:

> instructions in the README.md

If there are special procedures to set up a repository, I suggest to write them (or a note about them) into the [Arch Wiki entry of your repo](https://wiki.archlinux.org/title/Unofficial_user_repositories#jk-aur), e.g.

> Steps to get this repository working: See [README.md](https://github.com/jstkdng/aur/blob/master/README.md).


Regards!

-- 
Wählt man eine der Antworten zu dieser Frage zufällig aus, wie hoch ist
die Wahrscheinlichkeit, dass sie korrekt ist?

a) 25 %
b)  0 %
c) 50 %
d) 25 %

**Comment by jstkdng** [comment]
I've replaced my mirror repository with OBS's own repository so this should no longer be a problem, closing.

**Comment by dreirund** [comment]
On Sun, 08 Aug 2021 07:39:07 -0700, JustKidding
***@***.***> wrote about "Re: [jstkdng/aur] Arch Linux
repository `jk-aur`: Key ID discrepancy. (#10)":

> I've replaced my mirror repository with OBS's own repository so this
> should no longer be a problem, closing.

Can you please update

https://wiki.archlinux.org/title/unofficial_user_repositories#jk-aur

?

Regards!


-- 
I'll catch you if you fall.
                      - floor
