### ISSUE TITLE
maximum file size exceeded from download.opensuse.org

### ISSUE THREAD

**Issue by quite** [jstkdng/aur#11]
I'm getting this when trying to install from the new source. Never seen this msg before!

```
:: Retrieving packages...
 ungoogled-chromium-92.0.4515.131-1-x86_64.pkg.tar.zst failed to download
error: failed retrieving file 'ungoogled-chromium-92.0.4515.131-1-x86_64.pkg.tar.zst' from download.opensuse.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
error installing repo packages
``

**Comment by devvick** [comment]
Same here. Looks like chromium is banned on OBS:
https://en.opensuse.org/openSUSE:Build_Service_application_blacklist#Software_with_other_legal_implications

**Comment by jstkdng** [comment]
That is a curl error, I think the file size is in the database but when downloading the file is actually larger. Some solutions I found online:
- Redownload the database: `sudo pacman -Syy`
- Change xfer command con pacman.conf to wget

**Comment by quite** [comment]
External `XferCommand` like wget or curl is only used if that option is set. I got the error without it being set. In any case, it ought to work with any common transfer setting.

After `pacman -Syy` I can install the package, with both builtin, curl and wget. But I'm also getting this error output:

```
(1/1) checking keys in keyring                                                                                                  [#############################################################################] 100%
error: ungoogled-chromium: unsupported signature format
(1/1) checking package integrity                                                                                                [#############################################################################] 100%
(1/1) loading package files                  
```

I'm using `yay` to install, but I guess the signature check is done by pacman...

**Comment by jstkdng** [comment]
ah that problem is related to OBS itself, nothing I can do about it, at least it installs. If it is working now then closing.
