### ISSUE TITLE
Please upload key to public keyserver

### ISSUE THREAD

**Issue by phunni** [jstkdng/aur#12]
I know you have instructions in the readme to import the key, but it would be soooo much easier if we could simply import a public key from a keyserver. The way I build my system is with scripts and other magic stuff and running those commands in the scripts would be much less striaghtforward than importing from a keyserver.

I doubt I'm the only one for whom this is true...

**Comment by jstkdng** [comment]
You know you could have done it yourself right? anyway, just added the key to keyserver.ubuntu.com
https://keyserver.ubuntu.com/pks/lookup?search=0x7627D0F8F60FBA35371A29E1AA6B2752759F9361&fingerprint=on&op=index

you're welcome and closing

**Comment by phunni** [comment]
Sorry - no, I did not  know that. Thank you.
