### ISSUE TITLE
Please create a seperate group for xorg-*-git packages

### ISSUE THREAD

**Issue by phunni** [jstkdng/aur#13]
I create my system using scripts (as, I suspect, do others) and so, these scripts fail when there is a clash between xorg-server and xorg-server-git etc. because I install the xorg group.

I understand you want the benefit of installing via a group, so please consider creating a new group for the *-git packages.

Please forgive me if I've misunderstood something about this.

**Comment by jstkdng** [comment]
why don't you install the xorg group before adding this repo?

**Comment by phunni** [comment]
It's not really possible with the scripts I use. The pacman setup is established early on - which makes sense.

**Comment by jstkdng** [comment]
Well, after some time thinking this I've decided not to change anything, I'd suggest installing separate packages and not the whole group, closing.
