### ISSUE TITLE
pacman -Syu: maximum redirect followed

### ISSUE THREAD

**Issue by quite** [jstkdng/aur#15]
Getting this sometimes from the repo at opensuse.org
```
failed retrieving file 'home_justkidding_arch_Arch.db' from download.opensuse.org : Maximum (10) redirects followed
```

It is usually overcome just by running pacman one or two times again. Guessing this might be some overall issue over att opensuse.org, but I'm completely unfamiliar with their eco-system, so I'm dropping the issue here...

**Comment by jstkdng** [comment]
Hello, I've never experienced this issue you are having. It may be a valid issue (or a transitory one) but I can't really do anything on my part. Try contacting the OBS team on their IRC or their mailing list, maybe they can do something about it.
Closing.
