### ISSUE TITLE
Discrepancies between repository information in Arch Wiki and here.

### ISSUE THREAD

**Issue by dreirund** [jstkdng/aur#16]
At https://wiki.archlinux.org/title/unofficial_user_repositories#jk-aur, the repository is mentioned as

```
[jk-aur]
Server = https://repo.vin.ovh/arch/$arch
```

On this [github's `README.md`](/jstkdng/aur/blob/master/README.md), it is mentioned as

```
[home_justkidding_arch_Arch]
Server = https://download.opensuse.org/repositories/home:/justkidding:/arch/Arch/$arch
```

The latter functions, for the first host name resolution does not work.

Also, the signing keys are different in both entries.

Can you check and maybe correct the [Arch Wiki entry](https://wiki.archlinux.org/title/unofficial_user_repositories#jk-aur)?

Thanks!

**Comment by jstkdng** [comment]
Just updated it. Thanks for pointing out the discrepancies. Closing.
