### ISSUE TITLE
GPG key appears to have expired on February 26, 2022

### ISSUE THREAD

**Issue by mmirg** [jstkdng/aur#17]
I'm running into a blocker with pacman as the repo's gpg appears to have expired.

```
pacman-key --list-keys justkidding@build.opensuse.org          
gpg: Note: trustdb not writable
pub   rsa2048 2019-12-19 [SC] [expired: 2022-02-26]
      7627D0F8F60FBA35371A29E1AA6B2752759F9361
uid           [ expired] home:justkidding OBS Project <home:justkidding@build.opensuse.org>
```
This seems to be reflected on the public keyserver as well:

> Search results for '0x7627D0F8F60FBA35371A29E1AA6B2752759F9361'
> Type bits/keyID            cr. time   exp time   key expir
> pub rsa2048/7627d0f8f60fba35371a29e1aa6b2752759f9361 2019-12-19T01:06:59Z
> 	 Hash=eece5f202258aeb861341ddf3e13012c
> 
> uid home:justkidding OBS Project <home:justkidding@build.opensuse.org>
> sig  sig  aa6b2752759f9361 2019-12-19T01:06:59Z **2022-02-26**T01:06:59Z ____________________ [selfsig]
> sig  sig  3b3011b76b9d6523 2019-12-19T01:06:59Z ____________________ ____________________ 3b3011b76b9d6523

**Comment by mmirg** [comment]
Apologies, the key is updates on the OpenSuse servers.

https://build.opensuse.org/project/keys_and_certificates/home:justkidding:arch

**Comment by jstkdng** [comment]
hmm, yeah it seems the key I uploaded to the keyserver has expired, I'll try to update it
