### ISSUE TITLE
GPG check failed on some mirrors of ungoogled-chromium 

### ISSUE THREAD

**Issue by codingCoffee** [jstkdng/aur#18]
Hey! Thanks for maintaining this repo. I primarily use it for the `ungoogled-chromium` package. 

I recently noticed that the package installation failed with the following error
```
error: ungoogled-chromium: signature from "home:justkidding OBS Project <home:justkidding@build.opensuse.org>" is invalid
:: File /var/cache/pacman/pkg/ungoogled-chromium-99.0.4844.82-1-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```
Some debugging led me to finding out that this repo has multiple [mirror servers](https://mirrorcache.opensuse.org/repositories/home:/justkidding:/arch/Arch/x86_64/ungoogled-chromium-99.0.4844.82-1-x86_64.pkg.tar.zst.mirrorlist) and the content served by ftp.gwdg.de, specifically [this version of ungoogled-chromium](https://ftp.gwdg.de/pub/opensuse/repositories/home:/justkidding:/arch/Arch/x86_64/ungoogled-chromium-99.0.4844.82-1-x86_64.pkg.tar.zst) is not the same as [this ungoogled-chromium](https://downloadcontent.opensuse.org/repositories/home:/justkidding:/arch/Arch/x86_64/ungoogled-chromium-99.0.4844.82-1-x86_64.pkg.tar.zst) built on opensuse build system. Although them being the same version. 

On my system, `ungoogled-chromium` was downloaded from the ftp.gwdg.de mirror, and the package failed the signature check. I'm not sure where I should be raising this issue since I'm sure the mirrors are not under your control. But given the signature checks were failing could be an indication of tampered packages being hosted, I thought I should open a github issue here. 

It seems https://mirror.firstyear.id.au/ and https://downloadcontent.opensuse.org are hosting the same package (potentially the correct one) and https://ftp.byfly.by/ and https://ftp.gwdg.de are hosting a different package (failing the GPG check)

**Comment by jstkdng** [comment]
Huh, have you verified that the checksums are the same? If they are not that could mean a bad actor is tampering with the packages or just a weird bug. If that's so then the OpenSUSE folks should be notified.

**Comment by codingCoffee** [comment]
Ahh, my bad. I think I jumped to conclusions too early. The checksums were the same for all the files. Though I'm not sure why the signatures didn't match up.

**Comment by jstkdng** [comment]
Really weird. If you use directly https://downloadcontent.opensuse.org you don't have issues when using https://download.opensuse.org because the later might redirect you to a bad mirror.
I'm gonna switch to it and also in the docs.
