### ISSUE TITLE
Glibc version mismatch

### ISSUE THREAD

**Issue by rakshazi** [jstkdng/aur#2]
Hello,

I got following error:
```
$ chromium 
/usr/lib/chromium/chromium: /usr/lib/libc.so.6: version `GLIBC_2.32' not found (required by /usr/lib/chromium/chromium)
```

Installed ungoogled-chromium version: `ungoogled-chromium-84.0.4147.135-1`

```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.1
Codename:       Mikah

 $ uname -r
5.8.1-3-MANJARO

$ yay glibc
1 core/glibc 2.31-5 (9.8 MiB 46.2 MiB) (Installed)
    GNU C Library
```

Could you lower glibc requirements, please?

**Comment by jstkdng** [comment]
UC is linked to the latest glibc version available on arch. You are using manjaro so can't really help you with that. You can always switch to arch.
