### ISSUE TITLE
obs got broken again

### ISSUE THREAD

**Issue by a51kot** [jstkdng/aur#20]
almost all of our packages are reporting this error

[   21s] ==> ERROR: Cannot find the gzip binary required for compressing man and info pages.

https://build.opensuse.org/project/monitor/home:justkidding:arch?arch_x86_64=1&defaults=0&failed=1&repo_Arch=1

**Comment by jstkdng** [comment]
indeed, seems like the suse guys decided to no longer install gzip in their arch builds for some reason. Fixed.
