### ISSUE TITLE
Chromium ungoogled ozone fails to start: libre2.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nemanjan00** [jstkdng/aur#3]
After recent update, chromium fails to start

```
/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.8: cannot open shared object file: No such file or directory
```
Package: `ungoogled-chromium-git` **85.0.4183.121.1.r2.gab0e678-1**

I expect rebuilding it would solve the issue

**Comment by jstkdng** [comment]
Yes, rebuilding should solve the issue, also, you should be using ungoogled-chromium as it is more up to date.

**Comment by d8f6** [comment]
@jstkdng Are you going to bump the version in this repo and do the rebuild and we should just wait for the update, or are you saying that we need to recompile this application ourselves from source in order to get a working version?

**Comment by jstkdng** [comment]
I'll bump once the OBS builds a package. In order to have a working version you could downgrade re2 in the meantime.
It should take around 3 hours, just wait until then and downgrade.
https://build.opensuse.org/package/live_build_log/home:justkidding:arch/ungoogled-chromium/standard/x86_64

**Comment by d8f6** [comment]
Gotcha. I'll wait for the new build (already downgraded re2, but the downgrade broke something else and I didn't want to use a hackish workaround). Thanks for the quick reply.

**Comment by jstkdng** [comment]
alright then, closing.

**Comment by nemanjan00** [comment]
Does `ungoogled-chromium` support ozone?

**Comment by jstkdng** [comment]
@nemanjan00 yes, you have to add these flags for it to work
```
--enable-features=UseOzonePlatform --ozone-platform=wayland
```
