### ISSUE TITLE
Add repo to ArchWiki

### ISSUE THREAD

**Issue by Rubo3** [jstkdng/aur#5]
Hi, I think it would be useful to have your repo on the ArchWiki page about [unofficial user repositories](https://wiki.archlinux.org/index.php/Unofficial_user_repositories), so that more people could find it. What do you think?

**Comment by jstkdng** [comment]
Why not, done.
https://wiki.archlinux.org/index.php/Unofficial_user_repositories#jk-aur

**Comment by Rubo3** [comment]
Thank you!
