### ISSUE TITLE
Didn't found maintained PKGBUILD for ungoogled-chromium-bin

### ISSUE THREAD

**Issue by asakura42** [jstkdng/aur#6]
And made it: https://github.com/asakura42/ungoogled-chromium-bin

If you have PKGBUILD for your binary files, pls send. (Cause original is better).

**Comment by jstkdng** [comment]
I have this one https://github.com/jstkdng/ungoogled-chromium-bin , I'm not maintaining it though. The best solution is to use one of the binary repositories in my opinion, feel free to pr if you'd like to maintain uc-bin.

**Comment by jstkdng** [comment]
no response from op for some time now, closing.
