### ISSUE TITLE
libjsoncpp error - ungoogled-chromium

### ISSUE THREAD

**Issue by gururise** [jstkdng/aur#7]
Latest ungoogled-chromium is looking for older version of libjsoncpp?

`error while loading shared libraries: libjsoncpp.so.22: cannot open shared object file: No such file or directory`

According to [arch packages](https://archlinux.org/packages/extra/x86_64/jsoncpp/), latest libjsoncpp provides libjsoncpp.so.24.

**Comment by BachoSeven** [comment]
That's odd, I don't even have the `libjsoncpp` package in my system(and latest ungoogled works fine). What does `pacman -Qi libjsoncpp` say about the reason it was installed (i.e. dependency of what)?

**Comment by jstkdng** [comment]
yeah that's weird, chromium isn't even linked to libjsoncpp (at least on my builds), are you using any binary repository? could be binary tampering thb.

**Comment by jstkdng** [comment]
no info for some time now from op, closing
