### ISSUE TITLE
New key?

### ISSUE THREAD

**Issue by asakura42** [jstkdng/aur#8]
Downloaded one of your packages from OBS and found:

```
gpg: Signature made Sat 13 Feb 2021 08:45:09 PM MSK
gpg:                using RSA key AA6B2752759F9361
gpg: Can't check signature: No public key
```

And this is not your key. 

```
gpg --recv-keys AA6B2752759F9361
gpg: keyserver receive failed: No data
```

I don't know about gpg too much, maybe it's just mistake.

**Comment by jstkdng** [comment]
I haven't changed my main key, try downloading from my repository.

**Comment by jstkdng** [comment]
no info from op for some time now, closing.
