### ISSUE TITLE
Rebuild request for ungoogled-chromium

### ISSUE THREAD

**Issue by ghost** [jstkdng/aur#9]
`/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory`

`core/icu` was updated to 69.1-1 today and the binary currently uses 68. Please rebuild when convenient, thanks!

**Comment by jstkdng** [comment]
Currently rebuilding.. will include it in the repo asap.

**Comment by jstkdng** [comment]
build finished and repo updated. closing.
